# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=coolstore
quarkus.datasource.password=coolstore
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/coolstore

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none

# Flyway
quarkus.flyway.migrate-at-start=true

# Reactive Messaging (in-memory connector replicates JMS topic pub/sub)
mp.messaging.outgoing.orders-outgoing.connector=smallrye-in-memory
mp.messaging.outgoing.orders-outgoing.merge=true
mp.messaging.incoming.orders.connector=smallrye-in-memory
mp.messaging.incoming.orders-notification.connector=smallrye-in-memory
