package com.redhat.coolstore.model;

import org.junit.After;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.util.Arrays;

import static org.junit.Assert.*;

public class OrderTest {

    private EntityManagerFactory emf;
    private EntityManager em;

    @BeforeEach
    public void setUp() {
        emf = Persistence.createEntityManagerFactory("primary");
        em = emf.createEntityManager();
    }

    @After
    public void tearDown() {
        if (em != null && em.isOpen()) em.close();
        if (emf != null && emf.isOpen()) emf.close();
    }

    @Test
    public void testFieldMapping() {
        Order order = new Order();
        order.setCustomerName("John Doe");
        order.setCustomerEmail("john@example.com");
        order.setOrderValue(100.0);
        order.setRetailPrice(120.0);
        order.setDiscount(-20.0);
        order.setShippingFee(5.99);
        order.setShippingDiscount(-5.99);

        assertEquals("John Doe", order.getCustomerName());
        assertEquals("john@example.com", order.getCustomerEmail());
        assertEquals(100.0, order.getOrderValue(), 0.001);
        assertEquals(120.0, order.getRetailPrice(), 0.001);
        assertEquals(-20.0, order.getDiscount(), 0.001);
        assertEquals(5.99, order.getShippingFee(), 0.001);
        assertEquals(-5.99, order.getShippingDiscount(), 0.001);
    }

    @Test
    public void testJpaRoundTripWithAutoGeneratedId() {
        Order order = new Order();
        order.setCustomerName("Jane Smith");
        order.setCustomerEmail("jane@example.com");
        order.setOrderValue(50.0);

        em.getTransaction().begin();
        em.persist(order);
        em.getTransaction().commit();

        assertTrue(order.getOrderId() > 0);

        em.clear();
        Order found = em.find(Order.class, order.getOrderId());
        assertNotNull(found);
        assertEquals("Jane Smith", found.getCustomerName());
        assertEquals("jane@example.com", found.getCustomerEmail());
    }

    @Test
    public void testOneToManyWithOrderItems() {
        OrderItem item1 = new OrderItem();
        item1.setProductId("PROD-1");
        item1.setQuantity(2);

        OrderItem item2 = new OrderItem();
        item2.setProductId("PROD-2");
        item2.setQuantity(1);

        Order order = new Order();
        order.setCustomerName("Bob");
        order.setCustomerEmail("bob@example.com");
        order.setOrderValue(75.0);
        order.setItemList(Arrays.asList(item1, item2));

        em.getTransaction().begin();
        em.persist(order);
        em.getTransaction().commit();
        em.clear();

        Order found = em.find(Order.class, order.getOrderId());
        assertNotNull(found);
        assertEquals(2, found.getItemList().size());
    }

    @Test
    public void testEmptyItemList() {
        Order order = new Order();
        assertNotNull(order.getItemList());
        assertEquals(0, order.getItemList().size());
    }
}
