package com.redhat.coolstore.model;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import jakarta.transaction.Transactional;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

@QuarkusTest
public class OrderTest {

    @Inject
    EntityManager em;

    @Test
    public void testFieldMapping() {
        Order order = new Order();
        order.setCustomerName("John Doe");
        order.setCustomerEmail("john@example.com");
        order.setOrderValue(100.0);
        order.setRetailPrice(120.0);
        order.setDiscount(-20.0);
        order.setShippingFee(5.99);
        order.setShippingDiscount(-5.99);

        assertEquals("John Doe", order.getCustomerName());
        assertEquals("john@example.com", order.getCustomerEmail());
        assertEquals(100.0, order.getOrderValue(), 0.001);
        assertEquals(120.0, order.getRetailPrice(), 0.001);
        assertEquals(-20.0, order.getDiscount(), 0.001);
        assertEquals(5.99, order.getShippingFee(), 0.001);
        assertEquals(-5.99, order.getShippingDiscount(), 0.001);
    }

    @Test
    @Transactional
    public void testJpaRoundTripWithAutoGeneratedId() {
        Order order = new Order();
        order.setCustomerName("Jane Smith");
        order.setCustomerEmail("jane@example.com");
        order.setOrderValue(50.0);

        em.persist(order);

        assertTrue(order.getOrderId() > 0);

        em.clear();
        Order found = em.find(Order.class, order.getOrderId());
        assertNotNull(found);
        assertEquals("Jane Smith", found.getCustomerName());
        assertEquals("jane@example.com", found.getCustomerEmail());
    }

    @Test
    @Transactional
    public void testOneToManyWithOrderItems() {
        OrderItem item1 = new OrderItem();
        item1.setProductId("PROD-1");
        item1.setQuantity(2);

        OrderItem item2 = new OrderItem();
        item2.setProductId("PROD-2");
        item2.setQuantity(1);

        Order order = new Order();
        order.setCustomerName("Bob");
        order.setCustomerEmail("bob@example.com");
        order.setOrderValue(75.0);
        order.setItemList(Arrays.asList(item1, item2));

        em.persist(order);
        em.clear();

        Order found = em.find(Order.class, order.getOrderId());
        assertNotNull(found);
        assertEquals(2, found.getItemList().size());
    }

    @Test
    public void testEmptyItemList() {
        Order order = new Order();
        assertNotNull(order.getItemList());
        assertEquals(0, order.getItemList().size());
    }
}
